name: flutter_recipes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7
  flutter: ">=3.38.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.4
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true
